/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWeightRouteImport } from './routes/_auth.weight'
import { Route as AuthWaterQualityRouteImport } from './routes/_auth.water-quality'
import { Route as AuthVaccinationsRouteImport } from './routes/_auth.vaccinations'
import { Route as AuthSuppliersRouteImport } from './routes/_auth.suppliers'
import { Route as AuthSalesRouteImport } from './routes/_auth.sales'
import { Route as AuthReportsRouteImport } from './routes/_auth.reports'
import { Route as AuthMortalityRouteImport } from './routes/_auth.mortality'
import { Route as AuthInvoicesRouteImport } from './routes/_auth.invoices'
import { Route as AuthFeedRouteImport } from './routes/_auth.feed'
import { Route as AuthFarmsRouteImport } from './routes/_auth.farms'
import { Route as AuthExpensesRouteImport } from './routes/_auth.expenses'
import { Route as AuthEggsRouteImport } from './routes/_auth.eggs'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCustomersRouteImport } from './routes/_auth.customers'
import { Route as AuthFarmsIndexRouteImport } from './routes/_auth.farms.index'
import { Route as AuthBatchesIndexRouteImport } from './routes/_auth.batches.index'
import { Route as AuthWeightNewRouteImport } from './routes/_auth.weight.new'
import { Route as AuthWaterQualityNewRouteImport } from './routes/_auth.water-quality.new'
import { Route as AuthVaccinationsNewRouteImport } from './routes/_auth.vaccinations.new'
import { Route as AuthSuppliersNewRouteImport } from './routes/_auth.suppliers.new'
import { Route as AuthSuppliersSupplierIdRouteImport } from './routes/_auth.suppliers.$supplierId'
import { Route as AuthSalesNewRouteImport } from './routes/_auth.sales.new'
import { Route as AuthReportsExportRouteImport } from './routes/_auth.reports.export'
import { Route as AuthInvoicesNewRouteImport } from './routes/_auth.invoices.new'
import { Route as AuthInvoicesInvoiceIdRouteImport } from './routes/_auth.invoices.$invoiceId'
import { Route as AuthFeedNewRouteImport } from './routes/_auth.feed.new'
import { Route as AuthFarmsNewRouteImport } from './routes/_auth.farms.new'
import { Route as AuthFarmsFarmIdRouteImport } from './routes/_auth.farms.$farmId'
import { Route as AuthExpensesNewRouteImport } from './routes/_auth.expenses.new'
import { Route as AuthEggsNewRouteImport } from './routes/_auth.eggs.new'
import { Route as AuthCustomersNewRouteImport } from './routes/_auth.customers.new'
import { Route as AuthBatchesNewRouteImport } from './routes/_auth.batches.new'
import { Route as AuthFarmsFarmIdIndexRouteImport } from './routes/_auth.farms.$farmId.index'
import { Route as AuthBatchesBatchIdIndexRouteImport } from './routes/_auth.batches.$batchId.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWeightRoute = AuthWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWaterQualityRoute = AuthWaterQualityRouteImport.update({
  id: '/water-quality',
  path: '/water-quality',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVaccinationsRoute = AuthVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuppliersRoute = AuthSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSalesRoute = AuthSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMortalityRoute = AuthMortalityRouteImport.update({
  id: '/mortality',
  path: '/mortality',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesRoute = AuthInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFeedRoute = AuthFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFarmsRoute = AuthFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExpensesRoute = AuthExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEggsRoute = AuthEggsRouteImport.update({
  id: '/eggs',
  path: '/eggs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFarmsIndexRoute = AuthFarmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFarmsRoute,
} as any)
const AuthBatchesIndexRoute = AuthBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWeightNewRoute = AuthWeightNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthWeightRoute,
} as any)
const AuthWaterQualityNewRoute = AuthWaterQualityNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthWaterQualityRoute,
} as any)
const AuthVaccinationsNewRoute = AuthVaccinationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthVaccinationsRoute,
} as any)
const AuthSuppliersNewRoute = AuthSuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSuppliersRoute,
} as any)
const AuthSuppliersSupplierIdRoute = AuthSuppliersSupplierIdRouteImport.update({
  id: '/$supplierId',
  path: '/$supplierId',
  getParentRoute: () => AuthSuppliersRoute,
} as any)
const AuthSalesNewRoute = AuthSalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSalesRoute,
} as any)
const AuthReportsExportRoute = AuthReportsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthInvoicesNewRoute = AuthInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthInvoicesRoute,
} as any)
const AuthInvoicesInvoiceIdRoute = AuthInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AuthInvoicesRoute,
} as any)
const AuthFeedNewRoute = AuthFeedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthFeedRoute,
} as any)
const AuthFarmsNewRoute = AuthFarmsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthFarmsRoute,
} as any)
const AuthFarmsFarmIdRoute = AuthFarmsFarmIdRouteImport.update({
  id: '/$farmId',
  path: '/$farmId',
  getParentRoute: () => AuthFarmsRoute,
} as any)
const AuthExpensesNewRoute = AuthExpensesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthExpensesRoute,
} as any)
const AuthEggsNewRoute = AuthEggsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthEggsRoute,
} as any)
const AuthCustomersNewRoute = AuthCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthCustomersRoute,
} as any)
const AuthBatchesNewRoute = AuthBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFarmsFarmIdIndexRoute = AuthFarmsFarmIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFarmsFarmIdRoute,
} as any)
const AuthBatchesBatchIdIndexRoute = AuthBatchesBatchIdIndexRouteImport.update({
  id: '/batches/$batchId/',
  path: '/batches/$batchId/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AuthCustomersRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/eggs': typeof AuthEggsRouteWithChildren
  '/expenses': typeof AuthExpensesRouteWithChildren
  '/farms': typeof AuthFarmsRouteWithChildren
  '/feed': typeof AuthFeedRouteWithChildren
  '/invoices': typeof AuthInvoicesRouteWithChildren
  '/mortality': typeof AuthMortalityRoute
  '/reports': typeof AuthReportsRouteWithChildren
  '/sales': typeof AuthSalesRouteWithChildren
  '/suppliers': typeof AuthSuppliersRouteWithChildren
  '/vaccinations': typeof AuthVaccinationsRouteWithChildren
  '/water-quality': typeof AuthWaterQualityRouteWithChildren
  '/weight': typeof AuthWeightRouteWithChildren
  '/batches/new': typeof AuthBatchesNewRoute
  '/customers/new': typeof AuthCustomersNewRoute
  '/eggs/new': typeof AuthEggsNewRoute
  '/expenses/new': typeof AuthExpensesNewRoute
  '/farms/$farmId': typeof AuthFarmsFarmIdRouteWithChildren
  '/farms/new': typeof AuthFarmsNewRoute
  '/feed/new': typeof AuthFeedNewRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthInvoicesNewRoute
  '/reports/export': typeof AuthReportsExportRoute
  '/sales/new': typeof AuthSalesNewRoute
  '/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/suppliers/new': typeof AuthSuppliersNewRoute
  '/vaccinations/new': typeof AuthVaccinationsNewRoute
  '/water-quality/new': typeof AuthWaterQualityNewRoute
  '/weight/new': typeof AuthWeightNewRoute
  '/batches': typeof AuthBatchesIndexRoute
  '/farms/': typeof AuthFarmsIndexRoute
  '/batches/$batchId': typeof AuthBatchesBatchIdIndexRoute
  '/farms/$farmId/': typeof AuthFarmsFarmIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AuthCustomersRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/eggs': typeof AuthEggsRouteWithChildren
  '/expenses': typeof AuthExpensesRouteWithChildren
  '/feed': typeof AuthFeedRouteWithChildren
  '/invoices': typeof AuthInvoicesRouteWithChildren
  '/mortality': typeof AuthMortalityRoute
  '/reports': typeof AuthReportsRouteWithChildren
  '/sales': typeof AuthSalesRouteWithChildren
  '/suppliers': typeof AuthSuppliersRouteWithChildren
  '/vaccinations': typeof AuthVaccinationsRouteWithChildren
  '/water-quality': typeof AuthWaterQualityRouteWithChildren
  '/weight': typeof AuthWeightRouteWithChildren
  '/batches/new': typeof AuthBatchesNewRoute
  '/customers/new': typeof AuthCustomersNewRoute
  '/eggs/new': typeof AuthEggsNewRoute
  '/expenses/new': typeof AuthExpensesNewRoute
  '/farms/new': typeof AuthFarmsNewRoute
  '/feed/new': typeof AuthFeedNewRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthInvoicesNewRoute
  '/reports/export': typeof AuthReportsExportRoute
  '/sales/new': typeof AuthSalesNewRoute
  '/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/suppliers/new': typeof AuthSuppliersNewRoute
  '/vaccinations/new': typeof AuthVaccinationsNewRoute
  '/water-quality/new': typeof AuthWaterQualityNewRoute
  '/weight/new': typeof AuthWeightNewRoute
  '/batches': typeof AuthBatchesIndexRoute
  '/farms': typeof AuthFarmsIndexRoute
  '/batches/$batchId': typeof AuthBatchesBatchIdIndexRoute
  '/farms/$farmId': typeof AuthFarmsFarmIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/customers': typeof AuthCustomersRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/eggs': typeof AuthEggsRouteWithChildren
  '/_auth/expenses': typeof AuthExpensesRouteWithChildren
  '/_auth/farms': typeof AuthFarmsRouteWithChildren
  '/_auth/feed': typeof AuthFeedRouteWithChildren
  '/_auth/invoices': typeof AuthInvoicesRouteWithChildren
  '/_auth/mortality': typeof AuthMortalityRoute
  '/_auth/reports': typeof AuthReportsRouteWithChildren
  '/_auth/sales': typeof AuthSalesRouteWithChildren
  '/_auth/suppliers': typeof AuthSuppliersRouteWithChildren
  '/_auth/vaccinations': typeof AuthVaccinationsRouteWithChildren
  '/_auth/water-quality': typeof AuthWaterQualityRouteWithChildren
  '/_auth/weight': typeof AuthWeightRouteWithChildren
  '/_auth/batches/new': typeof AuthBatchesNewRoute
  '/_auth/customers/new': typeof AuthCustomersNewRoute
  '/_auth/eggs/new': typeof AuthEggsNewRoute
  '/_auth/expenses/new': typeof AuthExpensesNewRoute
  '/_auth/farms/$farmId': typeof AuthFarmsFarmIdRouteWithChildren
  '/_auth/farms/new': typeof AuthFarmsNewRoute
  '/_auth/feed/new': typeof AuthFeedNewRoute
  '/_auth/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/_auth/invoices/new': typeof AuthInvoicesNewRoute
  '/_auth/reports/export': typeof AuthReportsExportRoute
  '/_auth/sales/new': typeof AuthSalesNewRoute
  '/_auth/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/_auth/suppliers/new': typeof AuthSuppliersNewRoute
  '/_auth/vaccinations/new': typeof AuthVaccinationsNewRoute
  '/_auth/water-quality/new': typeof AuthWaterQualityNewRoute
  '/_auth/weight/new': typeof AuthWeightNewRoute
  '/_auth/batches/': typeof AuthBatchesIndexRoute
  '/_auth/farms/': typeof AuthFarmsIndexRoute
  '/_auth/batches/$batchId/': typeof AuthBatchesBatchIdIndexRoute
  '/_auth/farms/$farmId/': typeof AuthFarmsFarmIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/eggs'
    | '/expenses'
    | '/farms'
    | '/feed'
    | '/invoices'
    | '/mortality'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/vaccinations'
    | '/water-quality'
    | '/weight'
    | '/batches/new'
    | '/customers/new'
    | '/eggs/new'
    | '/expenses/new'
    | '/farms/$farmId'
    | '/farms/new'
    | '/feed/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/reports/export'
    | '/sales/new'
    | '/suppliers/$supplierId'
    | '/suppliers/new'
    | '/vaccinations/new'
    | '/water-quality/new'
    | '/weight/new'
    | '/batches'
    | '/farms/'
    | '/batches/$batchId'
    | '/farms/$farmId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/eggs'
    | '/expenses'
    | '/feed'
    | '/invoices'
    | '/mortality'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/vaccinations'
    | '/water-quality'
    | '/weight'
    | '/batches/new'
    | '/customers/new'
    | '/eggs/new'
    | '/expenses/new'
    | '/farms/new'
    | '/feed/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/reports/export'
    | '/sales/new'
    | '/suppliers/$supplierId'
    | '/suppliers/new'
    | '/vaccinations/new'
    | '/water-quality/new'
    | '/weight/new'
    | '/batches'
    | '/farms'
    | '/batches/$batchId'
    | '/farms/$farmId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/customers'
    | '/_auth/dashboard'
    | '/_auth/eggs'
    | '/_auth/expenses'
    | '/_auth/farms'
    | '/_auth/feed'
    | '/_auth/invoices'
    | '/_auth/mortality'
    | '/_auth/reports'
    | '/_auth/sales'
    | '/_auth/suppliers'
    | '/_auth/vaccinations'
    | '/_auth/water-quality'
    | '/_auth/weight'
    | '/_auth/batches/new'
    | '/_auth/customers/new'
    | '/_auth/eggs/new'
    | '/_auth/expenses/new'
    | '/_auth/farms/$farmId'
    | '/_auth/farms/new'
    | '/_auth/feed/new'
    | '/_auth/invoices/$invoiceId'
    | '/_auth/invoices/new'
    | '/_auth/reports/export'
    | '/_auth/sales/new'
    | '/_auth/suppliers/$supplierId'
    | '/_auth/suppliers/new'
    | '/_auth/vaccinations/new'
    | '/_auth/water-quality/new'
    | '/_auth/weight/new'
    | '/_auth/batches/'
    | '/_auth/farms/'
    | '/_auth/batches/$batchId/'
    | '/_auth/farms/$farmId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/weight': {
      id: '/_auth/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AuthWeightRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/water-quality': {
      id: '/_auth/water-quality'
      path: '/water-quality'
      fullPath: '/water-quality'
      preLoaderRoute: typeof AuthWaterQualityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vaccinations': {
      id: '/_auth/vaccinations'
      path: '/vaccinations'
      fullPath: '/vaccinations'
      preLoaderRoute: typeof AuthVaccinationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers': {
      id: '/_auth/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthSuppliersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sales': {
      id: '/_auth/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthSalesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mortality': {
      id: '/_auth/mortality'
      path: '/mortality'
      fullPath: '/mortality'
      preLoaderRoute: typeof AuthMortalityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/feed': {
      id: '/_auth/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthFeedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/farms': {
      id: '/_auth/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AuthFarmsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/expenses': {
      id: '/_auth/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthExpensesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/eggs': {
      id: '/_auth/eggs'
      path: '/eggs'
      fullPath: '/eggs'
      preLoaderRoute: typeof AuthEggsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/farms/': {
      id: '/_auth/farms/'
      path: '/'
      fullPath: '/farms/'
      preLoaderRoute: typeof AuthFarmsIndexRouteImport
      parentRoute: typeof AuthFarmsRoute
    }
    '/_auth/batches/': {
      id: '/_auth/batches/'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthBatchesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/weight/new': {
      id: '/_auth/weight/new'
      path: '/new'
      fullPath: '/weight/new'
      preLoaderRoute: typeof AuthWeightNewRouteImport
      parentRoute: typeof AuthWeightRoute
    }
    '/_auth/water-quality/new': {
      id: '/_auth/water-quality/new'
      path: '/new'
      fullPath: '/water-quality/new'
      preLoaderRoute: typeof AuthWaterQualityNewRouteImport
      parentRoute: typeof AuthWaterQualityRoute
    }
    '/_auth/vaccinations/new': {
      id: '/_auth/vaccinations/new'
      path: '/new'
      fullPath: '/vaccinations/new'
      preLoaderRoute: typeof AuthVaccinationsNewRouteImport
      parentRoute: typeof AuthVaccinationsRoute
    }
    '/_auth/suppliers/new': {
      id: '/_auth/suppliers/new'
      path: '/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthSuppliersNewRouteImport
      parentRoute: typeof AuthSuppliersRoute
    }
    '/_auth/suppliers/$supplierId': {
      id: '/_auth/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthSuppliersRoute
    }
    '/_auth/sales/new': {
      id: '/_auth/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthSalesNewRouteImport
      parentRoute: typeof AuthSalesRoute
    }
    '/_auth/reports/export': {
      id: '/_auth/reports/export'
      path: '/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof AuthReportsExportRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/invoices/new': {
      id: '/_auth/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthInvoicesNewRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
    '/_auth/invoices/$invoiceId': {
      id: '/_auth/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
    '/_auth/feed/new': {
      id: '/_auth/feed/new'
      path: '/new'
      fullPath: '/feed/new'
      preLoaderRoute: typeof AuthFeedNewRouteImport
      parentRoute: typeof AuthFeedRoute
    }
    '/_auth/farms/new': {
      id: '/_auth/farms/new'
      path: '/new'
      fullPath: '/farms/new'
      preLoaderRoute: typeof AuthFarmsNewRouteImport
      parentRoute: typeof AuthFarmsRoute
    }
    '/_auth/farms/$farmId': {
      id: '/_auth/farms/$farmId'
      path: '/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof AuthFarmsFarmIdRouteImport
      parentRoute: typeof AuthFarmsRoute
    }
    '/_auth/expenses/new': {
      id: '/_auth/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthExpensesNewRouteImport
      parentRoute: typeof AuthExpensesRoute
    }
    '/_auth/eggs/new': {
      id: '/_auth/eggs/new'
      path: '/new'
      fullPath: '/eggs/new'
      preLoaderRoute: typeof AuthEggsNewRouteImport
      parentRoute: typeof AuthEggsRoute
    }
    '/_auth/customers/new': {
      id: '/_auth/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthCustomersNewRouteImport
      parentRoute: typeof AuthCustomersRoute
    }
    '/_auth/batches/new': {
      id: '/_auth/batches/new'
      path: '/batches/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof AuthBatchesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/farms/$farmId/': {
      id: '/_auth/farms/$farmId/'
      path: '/'
      fullPath: '/farms/$farmId/'
      preLoaderRoute: typeof AuthFarmsFarmIdIndexRouteImport
      parentRoute: typeof AuthFarmsFarmIdRoute
    }
    '/_auth/batches/$batchId/': {
      id: '/_auth/batches/$batchId/'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof AuthBatchesBatchIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthCustomersRouteChildren {
  AuthCustomersNewRoute: typeof AuthCustomersNewRoute
}

const AuthCustomersRouteChildren: AuthCustomersRouteChildren = {
  AuthCustomersNewRoute: AuthCustomersNewRoute,
}

const AuthCustomersRouteWithChildren = AuthCustomersRoute._addFileChildren(
  AuthCustomersRouteChildren,
)

interface AuthEggsRouteChildren {
  AuthEggsNewRoute: typeof AuthEggsNewRoute
}

const AuthEggsRouteChildren: AuthEggsRouteChildren = {
  AuthEggsNewRoute: AuthEggsNewRoute,
}

const AuthEggsRouteWithChildren = AuthEggsRoute._addFileChildren(
  AuthEggsRouteChildren,
)

interface AuthExpensesRouteChildren {
  AuthExpensesNewRoute: typeof AuthExpensesNewRoute
}

const AuthExpensesRouteChildren: AuthExpensesRouteChildren = {
  AuthExpensesNewRoute: AuthExpensesNewRoute,
}

const AuthExpensesRouteWithChildren = AuthExpensesRoute._addFileChildren(
  AuthExpensesRouteChildren,
)

interface AuthFarmsFarmIdRouteChildren {
  AuthFarmsFarmIdIndexRoute: typeof AuthFarmsFarmIdIndexRoute
}

const AuthFarmsFarmIdRouteChildren: AuthFarmsFarmIdRouteChildren = {
  AuthFarmsFarmIdIndexRoute: AuthFarmsFarmIdIndexRoute,
}

const AuthFarmsFarmIdRouteWithChildren = AuthFarmsFarmIdRoute._addFileChildren(
  AuthFarmsFarmIdRouteChildren,
)

interface AuthFarmsRouteChildren {
  AuthFarmsFarmIdRoute: typeof AuthFarmsFarmIdRouteWithChildren
  AuthFarmsNewRoute: typeof AuthFarmsNewRoute
  AuthFarmsIndexRoute: typeof AuthFarmsIndexRoute
}

const AuthFarmsRouteChildren: AuthFarmsRouteChildren = {
  AuthFarmsFarmIdRoute: AuthFarmsFarmIdRouteWithChildren,
  AuthFarmsNewRoute: AuthFarmsNewRoute,
  AuthFarmsIndexRoute: AuthFarmsIndexRoute,
}

const AuthFarmsRouteWithChildren = AuthFarmsRoute._addFileChildren(
  AuthFarmsRouteChildren,
)

interface AuthFeedRouteChildren {
  AuthFeedNewRoute: typeof AuthFeedNewRoute
}

const AuthFeedRouteChildren: AuthFeedRouteChildren = {
  AuthFeedNewRoute: AuthFeedNewRoute,
}

const AuthFeedRouteWithChildren = AuthFeedRoute._addFileChildren(
  AuthFeedRouteChildren,
)

interface AuthInvoicesRouteChildren {
  AuthInvoicesInvoiceIdRoute: typeof AuthInvoicesInvoiceIdRoute
  AuthInvoicesNewRoute: typeof AuthInvoicesNewRoute
}

const AuthInvoicesRouteChildren: AuthInvoicesRouteChildren = {
  AuthInvoicesInvoiceIdRoute: AuthInvoicesInvoiceIdRoute,
  AuthInvoicesNewRoute: AuthInvoicesNewRoute,
}

const AuthInvoicesRouteWithChildren = AuthInvoicesRoute._addFileChildren(
  AuthInvoicesRouteChildren,
)

interface AuthReportsRouteChildren {
  AuthReportsExportRoute: typeof AuthReportsExportRoute
}

const AuthReportsRouteChildren: AuthReportsRouteChildren = {
  AuthReportsExportRoute: AuthReportsExportRoute,
}

const AuthReportsRouteWithChildren = AuthReportsRoute._addFileChildren(
  AuthReportsRouteChildren,
)

interface AuthSalesRouteChildren {
  AuthSalesNewRoute: typeof AuthSalesNewRoute
}

const AuthSalesRouteChildren: AuthSalesRouteChildren = {
  AuthSalesNewRoute: AuthSalesNewRoute,
}

const AuthSalesRouteWithChildren = AuthSalesRoute._addFileChildren(
  AuthSalesRouteChildren,
)

interface AuthSuppliersRouteChildren {
  AuthSuppliersSupplierIdRoute: typeof AuthSuppliersSupplierIdRoute
  AuthSuppliersNewRoute: typeof AuthSuppliersNewRoute
}

const AuthSuppliersRouteChildren: AuthSuppliersRouteChildren = {
  AuthSuppliersSupplierIdRoute: AuthSuppliersSupplierIdRoute,
  AuthSuppliersNewRoute: AuthSuppliersNewRoute,
}

const AuthSuppliersRouteWithChildren = AuthSuppliersRoute._addFileChildren(
  AuthSuppliersRouteChildren,
)

interface AuthVaccinationsRouteChildren {
  AuthVaccinationsNewRoute: typeof AuthVaccinationsNewRoute
}

const AuthVaccinationsRouteChildren: AuthVaccinationsRouteChildren = {
  AuthVaccinationsNewRoute: AuthVaccinationsNewRoute,
}

const AuthVaccinationsRouteWithChildren =
  AuthVaccinationsRoute._addFileChildren(AuthVaccinationsRouteChildren)

interface AuthWaterQualityRouteChildren {
  AuthWaterQualityNewRoute: typeof AuthWaterQualityNewRoute
}

const AuthWaterQualityRouteChildren: AuthWaterQualityRouteChildren = {
  AuthWaterQualityNewRoute: AuthWaterQualityNewRoute,
}

const AuthWaterQualityRouteWithChildren =
  AuthWaterQualityRoute._addFileChildren(AuthWaterQualityRouteChildren)

interface AuthWeightRouteChildren {
  AuthWeightNewRoute: typeof AuthWeightNewRoute
}

const AuthWeightRouteChildren: AuthWeightRouteChildren = {
  AuthWeightNewRoute: AuthWeightNewRoute,
}

const AuthWeightRouteWithChildren = AuthWeightRoute._addFileChildren(
  AuthWeightRouteChildren,
)

interface AuthRouteChildren {
  AuthCustomersRoute: typeof AuthCustomersRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthEggsRoute: typeof AuthEggsRouteWithChildren
  AuthExpensesRoute: typeof AuthExpensesRouteWithChildren
  AuthFarmsRoute: typeof AuthFarmsRouteWithChildren
  AuthFeedRoute: typeof AuthFeedRouteWithChildren
  AuthInvoicesRoute: typeof AuthInvoicesRouteWithChildren
  AuthMortalityRoute: typeof AuthMortalityRoute
  AuthReportsRoute: typeof AuthReportsRouteWithChildren
  AuthSalesRoute: typeof AuthSalesRouteWithChildren
  AuthSuppliersRoute: typeof AuthSuppliersRouteWithChildren
  AuthVaccinationsRoute: typeof AuthVaccinationsRouteWithChildren
  AuthWaterQualityRoute: typeof AuthWaterQualityRouteWithChildren
  AuthWeightRoute: typeof AuthWeightRouteWithChildren
  AuthBatchesNewRoute: typeof AuthBatchesNewRoute
  AuthBatchesIndexRoute: typeof AuthBatchesIndexRoute
  AuthBatchesBatchIdIndexRoute: typeof AuthBatchesBatchIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCustomersRoute: AuthCustomersRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthEggsRoute: AuthEggsRouteWithChildren,
  AuthExpensesRoute: AuthExpensesRouteWithChildren,
  AuthFarmsRoute: AuthFarmsRouteWithChildren,
  AuthFeedRoute: AuthFeedRouteWithChildren,
  AuthInvoicesRoute: AuthInvoicesRouteWithChildren,
  AuthMortalityRoute: AuthMortalityRoute,
  AuthReportsRoute: AuthReportsRouteWithChildren,
  AuthSalesRoute: AuthSalesRouteWithChildren,
  AuthSuppliersRoute: AuthSuppliersRouteWithChildren,
  AuthVaccinationsRoute: AuthVaccinationsRouteWithChildren,
  AuthWaterQualityRoute: AuthWaterQualityRouteWithChildren,
  AuthWeightRoute: AuthWeightRouteWithChildren,
  AuthBatchesNewRoute: AuthBatchesNewRoute,
  AuthBatchesIndexRoute: AuthBatchesIndexRoute,
  AuthBatchesBatchIdIndexRoute: AuthBatchesBatchIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
